version: "3"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    command: /bin/sh docker_dev_start.sh
    # ports: -"8080:4000"
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: blork_elixir
      POSTGRES_USER: backend_real
    ports:
      - "5432:5432"
