version: "3"
services:
  phoenix:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: blork_elixir
      POSTGRES_USER: backend_real
